######################## default configuration ####################
baseURL = "https://javaconcurrency.symentis.pl/"
languageCode = "pl"
title = "Współbieżność w Javie"
theme = "influencer"
summaryLength = "10"
paginate = 6
enableRobotsTXT = true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "O szkoleniu"
  URL = "book"
  weight = 1
  
  [[menu.main]]
  name = "Tematy"
  URL = "chapter"
  weight = 2
  
  # [[menu.main]]
  # name = "Opinie"
  # URL = "review"
  # weight = 3
  
  [[menu.main]]
  name = "Trener"
  URL = "author"
  weight = 4
  
  # [[menu.main]]
  # name = "Blog"
  # URL = "blog"
  # weight = 5
  
  [[menu.main]]
  name = "Kontakt"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = "https://symentis.pl/wp-content/uploads/2017/06/symentis-logo.png"
home = "Home"
# Meta data
description = "Szkolenie Java concurrency primitives, Java memory model i java.util.concurrent w praktyce.Kurs online dla początkujących."
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "UA-35040931-2" # Your ID
# copyright
copyright = "Copyright &copy; 2019 [GetHugoThemes](https://gethugothemes.com) All Rights Reserved"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = false

  
############################# Footer ########################
[params.footer]
content = "Symentis to nie tylko firma dostarczająca szkoleń i usług konsultacyjnych w obszarze rozwoju oprogramowania, architektury systemów IT i rozwoju organizacji (w szczególności działów R&D). Symentis to przede wszystkim grupa profesjonalistów, z wieloletnim doświadczeniem w branży rozwoju oprogramowania, którzy swoje doświadczenie mogą potwierdzić nie tylko poprzez udział w międzynarodowych projektach, ale także poprzez udział w projektach „open source”, a także jako aktywni członkowie lokalnych społeczności programistów, organizujących i biorących udział w konferencjach, członkowie rad programowych i prezenterzy."


############################# post share ###################
[[params.share]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.share]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"